### ISSUE TITLE
hey

### ISSUE THREAD

**Issue by axlkvh** [marius851000/pmd_sir0#1]
how do i download and/or use this?

**Comment by marius851000** [comment]
That's a weird question (coming from a newly created account)

Do you even know what this does? You may want to look up SkyTemple instead (otherwise you can always reply back)

**Comment by axlkvh** [comment]
I know what it does but I don’t see any packages or a readme.md file
Do I just download the repo directly?

**Comment by axlkvh** [comment]
did you think i was editing a pokemon game? no, i was editing 9 persons 9 hours 9 doors.

**Comment by marius851000** [comment]
So you say that this game use sir0? That's interesting to know.

So, the answer is that this code is a library. There is no executable, as it instead is a piece of code that can be reused for making tools.

Sir0 is a wrapper format. It doesn't define any data in particular, and instead just help the game during loading the data into RAM from ROM.

I have never looked at that game, so I can't help, but if you are interested the format is documented on the Project Pokemon website.

If you say me what you want to edit, maybe I can direct you to the good tools, but I think your best luck is still asking on the SkyTemple Discord server. There might be some filed that share the format with EoS, given it's made by Chunsoft.

(and I'm not interested in helping with that. I'm busy with other things. I'll still take a quick look to see if there's any WAN file.)

**Comment by axlkvh** [comment]
I don’t think the 999 nds rom has a wan file
